export default [
  {
    id: 1,
    zone: "RS",
    site_coverage: 45,
    max_height: 10.5,
    storeys: 3,
    description: "Small Scale Residential zone",
    comment:
      "A variety of housing forms up to three storeys in height can be built in the RS zone, including detached, attached, and multi-unit housing",
    city_id: 1,
    category_id: 1,
  },

  {
    id: 2,
    zone: "RSF",
    site_coverage: 55,
    max_height: 12,
    storeys: 3,
    description: "Small Scale Flex Residential zone",
    comment:
      "The RSF zone allows for a range of small scale residential development up to three storeys in height, including detached, attached, and multiunit residential housing",
    city_id: 1,
    category_id: 1,
  },

  {
    id: 3,
    zone: "RSM",
    site_coverage: 60,
    max_height: 14,
    storeys: 4,
    description: "Small-Medium Scale Transition Residential zone",
    comment:
      "The RSM zone allows for row housing and multiunit housing up to three or four storeys in height",
    city_id: 1,
    category_id: 1,
  },

  {
    id: 4,
    zone: "RM",
    site_coverage: 230,
    max_height: 16,
    storeys: 4,
    description: "Medium Scale Residential zone",
    comment: "Minimum of 45 Dwellings",
    city_id: 1,
    category_id: 1,
  },
  {
    id: 5,
    zone: "RM",
    site_coverage: 300,
    max_height: 23,
    storeys: "6",
    description: "Medium Scale Residential zone",
    comment: "Minimum of 75 Dwellings",
    city_id: 1,
    category_id: 1,
  },
  {
    id: 6,
    zone: "RM",
    site_coverage: 380,
    max_height: 28,
    storeys: "8",
    description: "Medium Scale Residential zone",
    comment: "Minimum of 90 Dwellings",
    city_id: 1,
    category_id: 1,
  },

  {
    id: 7,
    zone: "RL",
    site_coverage: 450,
    max_height: 50,
    storeys: 15,
    description: "Large Scale Residential zone",
    comment:
      "The RL zone allows for high rise housing forms ranging from approximately nine to fifteen stories in height",
    city_id: 1,
    category_id: 1,
  },

  {
    id: 8,
    zone: "RL",
    site_coverage: 550,
    max_height: 65,
    storeys: 20,
    description: "Large Scale Residential zone",
    comment:
      "The RL zone allows for high rise housing forms ranging from approximately nine to twenty stories in height",
    city_id: 1,
    category_id: 1,
  },

  {
    id: 9,
    zone: "MUN",
    site_coverage: 90,
    max_height: 16,
    storeys: 4,
    description: "Neighbourhood Mixed Use zone",
    comment: "Commercial is required on the ground floor",
    city_id: 1,
    category_id: 2,
  },

  {
    id: 10,
    zone: "MU",
    site_coverage: 90,
    max_height: 16,
    storeys: "4",
    description: "Mixed Use zone",
    comment:
      "The MU zone allows for a range of building heights and a mix of residential and nonresidential uses",
    city_id: 1,
    category_id: 2,
  },

  {
    id: 11,
    zone: "CN",
    site_coverage: 200,
    max_height: 12,
    storeys: "3",
    description: "Neighbourhood Commercial zone",
    comment:
      "The intent of this zone is to support local nodes by making goods, services and amenities more accessible to residents within their neighbourhood",
    city_id: 1,
    category_id: 3,
  },

  {
    id: 12,
    zone: "CG",
    site_coverage: 350,
    max_height: 16,
    storeys: "4",
    description: "General Commercial zone",
    comment:
      "Intense commercial activity, such as offices and shopping centres",
    city_id: 1,
    category_id: 3,
  },

  {
    id: 13,
    zone: "CG",
    site_coverage: 350,
    max_height: 30,
    storeys: 9,
    description: "General Commercial zone",
    comment: "Hotel",
    city_id: 1,
    category_id: 3,
  },

  {
    id: 14,
    zone: "CB",
    site_coverage: 350,
    max_height: 16,
    storeys: 4,
    description: "Business Commercial zone",
    comment:
      "Opportunities for a variety of commercial and light industrial activities",
    city_id: 1,
    category_id: 3,
  },

  {
    id: 15,
    zone: "CB",
    site_coverage: 350,
    max_height: 30,
    storeys: 9,
    description: "Business Commercial zone",
    comment: "Hotel",
    city_id: 1,
    category_id: 3,
  },
  {
    id: 16,
    zone: "BE",
    site_coverage: 160,
    max_height: 16,
    storeys: 4,
    description: "Business Emplyoment zone",
    comment:
      "light industrial and limited commercial development and functions as a transition zone from nonindustrial zones to medium and heavy industrial zones. Because of its potential to be located nearby other non-industrial areas, the BE zone includes a higher standard of design than other industrial zones",
    city_id: 1,
    category_id: 3,
  },

  {
    id: 17,
    zone: "IM",
    site_coverage: 200,
    max_height: 18,
    storeys: 4,
    description: "Medium Industrial zone",
    comment: "The IM zone primarily allows for minor industrial development",
    city_id: 1,
    category_id: 3,
  },

  {
    id: 18,
    zone: "IH",
    site_coverage: 200,
    max_height: 30,
    storeys: 9,
    description: "Heavy Industrial zone",
    comment:
      "Allows for major industrial development, major utilities, and natural resource development",
    city_id: 1,
    category_id: 3,
  },

  {
    id: 19,
    zone: "R1A",
    site_coverage: 40,
    max_height: 10,
    storeys: 2,
    description: "Single detached Residential A",
    comment:
      "To provide for single dwellings on residential lots with a minimum width of 15.0 m",
    city_id: 5,
    category_id: 1,
  },
  {
    id: 20,
    zone: "R1B",
    site_coverage: 40,
    max_height: 9.1,
    storeys: 2,
    description: "Single detached Residential B",
    comment:
      "To provide for single dwellings on residential lots with a minimum width of 12.0 m",
    city_id: 5,
    category_id: 1,
  },
  {
    id: 21,
    zone: "R1C",
    site_coverage: 42.5,
    max_height: 9.1,
    storeys: 2,
    description: "Single detached Residential C",
    comment:
      "To provide for single dwellings on residential lots with a minimum width of 10.6 m",
    city_id: 5,
    category_id: 1,
  },
  {
    id: 22,
    zone: "R2A",
    site_coverage: 40,
    max_height: 10,
    storeys: 2,
    description: "Single detached Residential",
    comment:
      "To provide primarily for semi-detached dwellings on residential lots with a minimum width of 7.6 m per lot",
    city_id: 5,
    category_id: 1,
  },

  {
    id: 23,
    zone: "R2B",
    site_coverage: 40,
    max_height: 10,
    storeys: 2,
    description: "low Density Residential",
    comment:
      "To provide for single detached dwellings and semi-detached housing on a planned site basis with internal roadways",
    city_id: 5,
    category_id: 1,
  },

  {
    id: 24,
    zone: "R3",
    site_coverage: 40,
    max_height: 10,
    storeys: 2,
    description: "Multiple Residential",
    comment:
      "To provide for townhouse dwellings, either with internal site roadways or as street-facing fee-simple development",
    city_id: 5,
    category_id: 1,
  },
  {
    id: 25,
    zone: "R4",
    site_coverage: 40,
    max_height: 14,
    storeys: 3,
    description: "Medium Density Multiple Residential",
    comment:
      "To provide for medium-density multiple dwellings, primarily as low rise apartment dwellings",
    city_id: 5,
    category_id: 1,
  },
  {
    id: 26,
    zone: "R5",
    site_coverage: 40,
    max_height: 40,
    storeys: 12,
    description: "High Density Multiple Residential",
    comment:
      "To provide for a high-density multiple housing, primarily as high rise apartments",
    city_id: 5,
    category_id: 1,
  },
  {
    id: 27,
    zone: "RE",
    site_coverage: 40,
    max_height: 10,
    storeys: 2,
    description: "Estate Residential",
    comment:
      "To foster an estate residential lifestyle on properties of 1250 m2 or larger",
    city_id: 5,
    category_id: 1,
  },

  {
    id: 28,
    zone: "RM",
    site_coverage: 42.5,
    max_height: 4.5,
    storeys: 1,
    description: "Manufactured Home",
    comment:
      "To provide for housing in a planned manufactured housing community in accordance with the Municipal Development Plan",
    city_id: 5,
    category_id: 1,
  },

  {
    id: 29,
    zone: "C1",
    site_coverage: 100,
    max_height: 12,
    storeys: 3,
    description: "Community commercial",
    comment:
      "To provide for a broad range of services needed on a day to day basis by residents of urban neighbourhoods, hamlets, or rural areas",
    city_id: 5,
    category_id: 3,
  },
  {
    id: 30,
    zone: "C2",
    site_coverage: 200,
    max_height: 14,
    storeys: 4,
    description: "Arterial commercial",
    comment:
      "To provide for a diversity of commercial businesses in planned centres displaying a high standard of appearance and design",
    city_id: 5,
    category_id: 3,
  },
  {
    id: 31,
    zone: "C3",
    site_coverage: 200,
    max_height: 10,
    storeys: 2,
    description: "Highway commercial",
    comment:
      "To provide for a diversity of commercial, recreation, and tourist uses, largely intended for the public travelling along highways or in conjunction with tourist attractions",
    city_id: 5,
    category_id: 3,
  },
  {
    id: 32,
    zone: "C3",
    site_coverage: 200,
    max_height: 16,
    storeys: 4,
    description: "Highway commercial",
    comment: "Hotel",
    city_id: 5,
    category_id: 3,
  },
  {
    id: 33,
    zone: "C4",
    site_coverage: 200,
    max_height: 40,
    storeys: 12,
    description: "Major commercial",
    comment:
      "To provide a wide range of commercial, institutional, cultural, entertainment, and other services in central locations to serve Sherwood Park and beyond",
    category_id: 3,
    city_id: 5,
  },
  {
    id: 34,
    zone: "C5",
    site_coverage: 100,
    max_height: 12,
    storeys: 3,
    description: "Service commercial",
    comment:
      "To provide for a compatible mix of low intensity business and service commercial uses in planned centres with good visibility and accessibility",
    category_id: 3,
    city_id: 5,
  },
  {
    id: 35,
    zone: "ILT",
    site_coverage: 50,
    max_height: 15,
    storeys: 4,
    description: "Light Industrial",
    comment:
      "To provide an area that will facilitate services or businesses of an industrial nature which do not create or generate nuisance factors outside an enclosed building",
    category_id: 3,
    city_id: 5,
  },

  {
    id: 36,
    zone: "IM",
    site_coverage: 200,
    max_height: 18,
    storeys: 5,
    description: "Medium Industrial",
    comment:
      "To provide for a broad range of compatible commercial and industrial uses, some of which have outdoor storage or activities",
    category_id: 3,
    city_id: 5,
  },
  {
    id: 37,
    zone: "MI",
    site_coverage: 50,
    max_height: 40,
    storeys: 12,
    description: "Major Institutional",
    comment:
      "The purpose of this Zoning District is to provide for major institutional and community services uses and facilities to serve the County and the surrounding area",
    category_id: 3,
    city_id: 5,
  },
  {
    id: 38,
    category_id: 1,
    city_id: 2,
    zone: "R1",
    site_coverage: 15,
    max_height: 12,
    storeys: 3,
    description: "Country Residential District",
    comment:
      "To provide for multi-lot residential subdivisions in rural areas where parcel size is determined through limited servicing availability and associated regulations",
  },
  {
    id: 39,
    city_id: 2,
    category_id: 1,
    zone: "R2",
    site_coverage: 35,
    max_height: 12,
    storeys: 3,
    description: "Country Estate Residential District",
    comment:
      "This district accommodates multi-lot estate residential subdivisions with the provision of both municipal water and sanitary services.",
  },
  {
    id: 40,
    category_id: 1,
    city_id: 2,
    zone: "R3",
    site_coverage: 35,
    max_height: 12,
    storeys: 3,
    description: "Hamlet Unserviced District",
    comment:
      "This district accommodates residential development within traditional County hamlets that have municipal servicing constraints and are limited to private or communal sources, only partial municipal servicing or areas of the hamlet where provision of servicing cannot be accommodated.",
  },
  {
    id: 41,
    category_id: 1,
    city_id: 2,
    zone: "R4",
    site_coverage: 35,
    max_height: 12,
    storeys: 3,
    description: "Hamlet Serviced District",
    comment:
      "This district accommodates residential development within traditional County hamlets that have full municipal servicing available.",
  },
  {
    id: 42,
    category_id: 1,
    city_id: 2,
    zone: "R5",
    site_coverage: 55,
    max_height: 14.5,
    storeys: 4,
    description: "Multi-Family District",
    comment:
      "This district will accommodate a range of residential development forms including a semi-detached dwelling, duplex, and/or town house.",
  },
  {
    id: 43,
    category_id: 1,
    city_id: 2,
    zone: "R6",
    site_coverage: 55,
    max_height: 5,
    storeys: 2,
    description: "Modular Dwelling District",
    comment:
      "This district accommodates leasehold residential development in the form of modular dwellings and maintains the character of land lease communities.",
  },
  {
    id: 44,
    category_id: 1,
    city_id: 2,
    zone: "R7",
    site_coverage: 55,
    max_height: 14.5,
    storeys: 4,
    description: "Transitional valley Residential District",
    comment:
      "This district will accommodate a range of residential development forms",
  },
  {
    id: 45,
    category_id: 1,
    city_id: 4,
    zone: "BRR",
    site_coverage: 65,
    max_height: 3,
    storeys: 1,
    description: "Bareland Recreational Resort District",
    comment:
      "To provide for condominium Recreational Vehicle resort development in association with amenity features, and in compliance with an approved plan in accordance with the County’s statutory plan hierarchy",
  },
  {
    id: 46,
    category_id: 1,
    city_id: 4,
    zone: "CRWL",
    site_coverage: 30,
    max_height: 3,
    storeys: 1,
    description: "Country Residential Work / Live District",
    comment:
      "To accommodate the development of all levels of Home Based Businesses within a tradition country residential setting, while ensuring compatibility with surrounding residential land uses.",
  },
  {
    id: 47,
    category_id: 1,
    city_id: 4,
    zone: "EUV R1",
    site_coverage: 50,
    max_height: 6,
    storeys: 2,
    description: "Entwistle Urban Village District Single Family",
    comment:
      "To accommodate for a wide range of compatible residential and commercial uses that are traditional in Entwistle.",
  },
  {
    id: 48,
    category_id: 1,
    city_id: 4,
    zone: "EUV R2",
    site_coverage: 80,
    max_height: 9,
    storeys: 3,
    description: "Residential Medium Density District",
    comment:
      "This district is intended to accommodate a variety of low to medium density housing types",
  },
  {
    id: 49,
    category_id: 1,
    city_id: 4,
    zone: "EUV R3",
    site_coverage: 80,
    max_height: 9,
    storeys: 3,
    description: "Residential High Density District",
    comment:
      "This district is generally intended to accommodate medium to high density housing",
  },
  {
    id: 50,
    category_id: 1,
    city_id: 4,
    zone: "LSR",
    site_coverage: 40,
    max_height: 6,
    storeys: 2,
    description: "Lakeshore Residential District",
    comment:
      "To provide for development and redevelopment of smaller, pre-existing Parcels along the lakeshore of Wabamun Lake, Jackfish Lake and Isle Lake. The district is intended to not allow for new subdivisions.",
  },
  {
    id: 51,
    category_id: 1,
    city_id: 4,
    zone: "RC",
    site_coverage: 40,
    max_height: 6,
    storeys: 2,
    description: "Rural Centre District",
    comment:
      "To provide for a range of residential and non-residential land uses that are traditional in the following Rural Centres: Carvel, Duffield, Fallis, Gainford, Keephills, Magnolia and Tomahawk, excluding Entwistle.",
  },
  {
    id: 52,
    category_id: 3,
    city_id: 4,
    zone: "EUV C1",
    site_coverage: 50,
    max_height: 6,
    storeys: 2,
    description: "Main Street Commercial",
    comment:
      "This district is generally intended to accommodate a variety of office, retail and service commercial outlets to serve the Village.",
  },
  {
    id: 53,
    category_id: 3,
    city_id: 4,
    zone: "EUV UR",
    site_coverage: 80,
    max_height: 6,
    storeys: 2,
    description: "Urban Reserve",
    comment:
      "This land use district is generally intended to reserve those areas within the Village that are rural in character or land use for development that is urban in land use and density.",
  },
  {
    id: 54,
    category_id: 3,
    city_id: 4,
    zone: "HC",
    site_coverage: 50,
    max_height: 9,
    storeys: 3,
    description: "Highway Commerical District ",
    comment:
      "To accommodate a diverse range of high quality commercial, recreation and tourism type of uses to serve the travelling public and that will benefit from exposure to high traffic volumes.",
  },
  {
    id: 55,
    category_id: 3,
    city_id: 4,
    zone: "BI",
    site_coverage: 60,
    max_height: 9,
    storeys: 3,
    description: "Business Industrial District",
    comment:
      "The purpose of this district is to accommodate a range of industrial and commercial uses which may have outdoor storage or work activities, in fully serviced business and industrial parks.",
  },
  {
    id: 56,
    category_id: 3,
    city_id: 4,
    zone: "MI",
    site_coverage: 60,
    max_height: 9,
    storeys: 3,
    description: "Medium Industrial District",
    comment:
      "The purpose of this district is to provide for a broad range of compatible industrial uses on fully serviced Parcels, some of which may require outdoor storage or activities. Any nuisance factor should not extend beyond the boundaries of the Parcel.",
  },
  {
    id: 57,
    category_id: 1,
    city_id: 3,
    zone: "RU1",
    site_coverage: 45,
    max_height: 11,
    storeys: 2,
    description: "Residential Urban 1 Distric",
    comment:
      "The purpose of this district is to provide for low density residential development within fully-serviced multi-lot residential subdivisions",
  },
  {
    id: 58,
    category_id: 1,
    city_id: 3,
    zone: "RU2",
    site_coverage: 55,
    max_height: 11,
    storeys: 2,
    description: "Residential Urban 2 District",
    comment:
      "The purpose of this district is to provide for medium density residential development within fully-serviced multi-lot residential subdivisions.",
  },
  {
    id: 59,
    category_id: 1,
    city_id: 3,
    zone: "RU3",
    site_coverage: 55,
    max_height: 11,
    storeys: 2,
    description: "Residential Urban 3 District",
    comment:
      "The purpose of this district is to provide for higher density residential development within fully-serviced multi-lot residential subdivisions.",
  },
  {
    id: 60,
    category_id: 1,
    city_id: 3,
    zone: "RM1",
    site_coverage: 55,
    max_height: 11,
    storeys: 2,
    description: "Residential Multi Family District",
    comment:
      "The purpose of this district is to provide for the development of fully serviced, higher density, multi-family residential complexes.",
  },
  {
    id: 61,
    category_id: 1,
    city_id: 3,
    zone: "TC",
    site_coverage: 150,
    max_height: 14,
    storeys: 3,
    description: "Town Center District",
    comment:
      "The purpose of this district is to provide for a range of mixed higher density residential, personal, commercial, and institutional uses.",
  },
  {
    id: 62,
    category_id: 3,
    city_id: 3,
    zone: "UC1",
    site_coverage: 50,
    max_height: 10,
    storeys: 2,
    description: "Urban Commercial 1 District",
    comment:
      "The purpose of this district is to provide for a range of commercial uses to meet basic and daily needs in close proximity to residential areas.",
  },
  {
    id: 63,
    category_id: 3,
    city_id: 3,
    zone: "UC2",
    site_coverage: 50,
    max_height: 14,
    storeys: 3,
    description: "Urban Commercial 2 District",
    comment:
      "The purpose of this district is to provide for a range of commercial uses to serve the larger Leduc County community.",
  },
  {
    id: 64,
    category_id: 3,
    city_id: 3,
    zone: "WLC",
    site_coverage: 25,
    max_height: 10,
    storeys: 2,
    description: "Wizard Lake Central District",
    comment:
      "The purpose of this district is to protect the integrity of the lake and watershed, preserve tree cover and minimize adverse environmental impacts while allowing for minimal development of recreational and agricultural uses as well as residential development on smaller lots at lower densities.",
  },
  {
    id: 65,
    category_id: 3,
    city_id: 3,
    zone: "WLW/CC",
    site_coverage: 25,
    max_height: 10,
    storeys: 2,
    description: "Wizard Lake Watershed/Conjuring Creek District",
    comment:
      "The purpose of this district is to protect the integrity of the lake and watershed, preserve tree cover and minimize adverse environmental impacts while allowing for minimal development of recreational and agricultural uses as well as residential development on larger lots at lower densities.",
  },
  {
    id: 66,
    category_id: 3,
    city_id: 3,
    zone: "WLW",
    site_coverage: 25,
    max_height: 10,
    storeys: 2,
    description: "Wizard Lake West District",
    comment:
      "The purpose of this district is to protect the integrity of the lake and watershed, preserve tree cover and minimize adverse environmental impacts while allowing for minimal development of recreational and agricultural uses as well as residential development on larger lots at lower densities.",
  },
  {
    id: 67,
    category_id: 3,
    city_id: 3,
    zone: "IB",
    site_coverage: 80,
    max_height: 10,
    storeys: 6,
    description: "Industrial Business District",
    comment:
      "The purpose of this district is to allow for development of a wide array of business/corporate offices, retail/commercial operations, entertainment facilities/complexes, and high standard accommodations.",
  },
  {
    id: 68,
    category_id: 3,
    city_id: 3,
    zone: "LI",
    site_coverage: 80,
    max_height: 10,
    storeys: 6,
    description: "Light Industrial District",
    comment:
      "The purpose of this district is to allow logistics and distribution land uses with opportunities for related and supporting land uses.",
  },
  {
    id: 69,
    category_id: 3,
    city_id: 3,
    zone: "UC3",
    site_coverage: 60,
    max_height: 14,
    storeys: 3,
    description: "Urban Commercial 3 District",
    comment:
      "The purpose of this district is to provide for development of large scale, commercial shopping centres, entertainment and cultural uses in comprehensively planned developments.",
  },
  {
    id: 70,
    category_id: 3,
    city_id: 3,
    zone: "MB",
    site_coverage: 50,
    max_height: 25.6,
    storeys: 6,
    description: "Manufacturing Business Incubation District",
    comment:
      "The purpose of this district is to allow for development, within a business park-like setting, of mixed-use live/work units combined with manufacturing and business development, for the purpose of business incubation, and to be operated in such a way as to create no disturbances outside of the enclosed buildings.",
  },
  {
    id: 71,
    category_id: 3,
    city_id: 3,
    zone: "IR",
    site_coverage: 50,
    max_height: 10,
    storeys: 2,
    description: "Industrial Reserve",
    comment:
      "The purpose of this district is generally intended to reserve those areas of the municipality which are rural in character or land use for industrial development until such time as a subdivision plan has been accepted in principal or approved for other specific uses not permitted in this district.",
  },
  {
    id: 72,
    category_id: 3,
    city_id: 3,
    zone: "C1",
    site_coverage: 100,
    max_height: 4,
    storeys: 1,
    description: "Commercial",
    comment:
      "The purpose of this district is to provide for the mixed-use development of retail and service outlets which offer a variety of goods and services and allow for existing residential developments or in combination with commercial development.",
  },
  {
    id: 73,
    category_id: 3,
    city_id: 3,
    zone: "RMHC ",
    site_coverage: 40,
    max_height: 4,
    storeys: 1,
    description: "Mobile Home Court",
    comment:
      "The purpose of this district is generally intended to provide for Mobile Home Courts.",
  },
  {
    id: 74,
    category_id: 3,
    city_id: 3,
    zone: "UR",
    site_coverage: 40,
    max_height: 10,
    storeys: 2,
    description: "Urban Reserve",
    comment:
      "The purpose of this district is generally intended to reserve those areas of the municipality which are rural in character or land use for urban development until such time as an area structure plan has been approved or a subdivision plan has been accepted in principal or approved for other specific uses not permitted in this district.",
  },
];
